name: AbilityCraft
version: 0.1
main: at.the2019.abilitycraft.Main
api-version: 1.16
authors: [ The2019 ]
description: The Plugin for Ability Craft

commands:
  givegrapplinghook:
    usage: /<Command>
    description: gives a Grappling Hook!
  givebloodscyth:
    usage: /<Command>
    description: gives a Blood Scyth!
  giveflower:
    usage: /<Command>
    description: Gives the Flower of Truth!
  givecanehoe:
    usage: /<Command>
    description: Gives the Suger Cane hoe!
  givepumkinaxe:
    usage: /<Command>
    description: Gives the Pumkin Axe!
  givemelonecapitor:
    usage: /<Command>
    description: Gives the Melone Capitor!
  givewot:
    usage: /<Command>
    description: Gives the Wand of Teleportation!